---
# Source: https://github.com/pharmaverse/admiralci
# Common workflows designed for Admiral
# but can be easily used by any other R package
name: Admiral Workflows

on:
  # 'workflow_dispatch' gives you the ability
  # to run this workflow on demand, anytime
  workflow_dispatch:
  # 'push' events are triggered when commits
  # are pushed to one of these branches
  push:
    branches:
      - main
      - devel
      - pre-release
      - test
  # 'pull_request' events are triggered when PRs are
  # created against one of these target branches.
  pull_request:
    branches:
      - main
      - devel
      - pre-release
      - test
  # 'release' events are triggered when...
  # you guessed it - when releases are made.
  release:
    types: [published]
  schedule:
    - cron: '21 13 * * 1,3,5'

# Docs on concurrency:
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: admiral-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Code Style
    uses: pharmaverse/admiralci/.github/workflows/style.yml@main
    if: github.event_name == 'pull_request'
    with:
      r-version: "3.6"
  spellcheck:
    name: Spelling
    uses: pharmaverse/admiralci/.github/workflows/spellcheck.yml@main
    if: github.event_name == 'pull_request'
    with:
      r-version: "3.6"
  readme:
    name: Render README
    uses: pharmaverse/admiralci/.github/workflows/readme-render.yml@main
    if: github.event_name == 'push'
    with:
      r-version: $R_VERSION
      # This workflow autoformats the README.md file after
      # it has been rendered. If you want to skip that,
      # set the following value to 'true'
      skip-md-formatting: false
  check:
    name: Check
    uses: pharmaverse/admiralci/.github/workflows/r-cmd-check.yml@main
    if: github.event_name == 'pull_request'
    with:
      # Control how you want the errors to manifest
      # by supplying the 'error_on' parameter to
      # rcmdcheck::rcmdcheck() here.
      error-on: error
  docs:
    name: Documentation
    uses: pharmaverse/admiralci/.github/workflows/pkgdown.yml@main
    if: github.event_name == 'push'
    with:
      r-version: "3.6"
      # Whether to skip multiversion docs
      # Note that if you have multiple versions of docs,
      # your URL links are likely to break due to path changes
      skip-multiversion-docs: false
  coverage:
    name: Code Coverage
    uses: nicholas-masel/admiralci/.github/workflows/code-coverage.yml@exclusion
    if: >
      github.event_name == 'push' || github.event_name == 'pull_request'
    with:
      r-version: "3.6"
      # Whether to skip code coverage badge creation
      # Setting to 'false' will require you to create
      # an orphan branch called 'badges' in your repository
      skip-coverage-badges: false
  links:
    name: Links
    uses: pharmaverse/admiralci/.github/workflows/links.yml@main
    if: >
      github.event_name == 'push' || github.event_name == 'pull_request'
  man-pages:
    name: Man Pages
    uses: pharmaverse/admiralci/.github/workflows/man-pages.yml@main
    if: github.event_name == 'pull_request'
    with:
      r-version: "3.6"
